### ISSUE TITLE
Clean up repository

### ISSUE THREAD

**Issue by AndreiSva** [martinval9/CliDM#2]
Currently this repository contains a lot of anti patters such as loose build and update scripts and even a prebuilt binary. Here's a roadmap for cleaning up the repository.

- [x]  Remove prebuilt binary from git
- [x] Replace install.sh with a makefile
- [x] Move images to a separate folder outside the project root
- [x] Remove verificar.py. It adds an extra python dependency, is incredibly inefficient and exemplifies some bad programming practices. It should be integrated in the C code.

**Comment by martinval9** [comment]
I have already made all the changes, thank you very much
